workflows:
  curiosity_build:
    name: Curiosity - Flutter Build
    environment:
      flutter: stable
      xcode: latest  # Solo se aplica si compilas para iOS
      vars:
        BUNDLE_ID: "com.ranty.curiosity"
        APP_NAME: "Curiosity"
        FLUTTER_BUILD_MODE: "release"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Analyze code
        script: |
          flutter analyze
      - name: Run tests
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build AAB
        script: |
          flutter build appbundle --release
      - name: (Optional) Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - margtezchichitasanti@gmail.com
