name: curiosity
description: Compra a domicilio a los mejores restaurantes en Loja. Encuentra cafeterías y el delicioso tamal lojano. Todos los días encontrarás restaurantes con envío gratis.

version: 1.71.77+77

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.1
  flutter_sim_country_code: ^0.1.2
  receive_sharing_intent: ^1.4.5
  credit_card_validator: ^2.1.0
  google_maps_flutter: ^2.12.2
  permission_handler: ^11.3.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.6
  crypto: ^3.0.3
  universal_platform: ^1.0.0+1
  flutter_local_notifications: ^19.2.1
  location: ^5.0.3
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.1

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.2.6
  firebase_storage: ^12.4.6
  firebase_dynamic_links: ^6.1.6 # ⚠️ discontinuado

  firebase_app_check: ^0.3.2+6

  flutter_sound: ^9.3.8
  socket_io_client: ^2.0.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  sqflite: ^2.3.2
  uuid: ^4.3.3
  image_picker: ^1.1.0
  flutter_native_image: ^0.0.6+1 # ⚠️ discontinuado
  mime_type: ^1.0.0
  connectivity_plus: ^5.0.2
  animate_do: ^3.0.2
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.1.3
  pin_input_text_field: ^4.5.0
  timer_builder: ^2.0.0
  shimmer_animation: ^2.1.0+1

  month_picker_dialog: ^6.0.3
  percent_indicator: ^4.2.3
  intl_phone_number_input: ^0.7.3+2
  slider_button: ^2.1.0

  flutter_touch_spin_2: ^0.0.2
  flutter_animation_progress_bar: ^2.2.1
  solid_bottom_sheet: ^0.1.10
  toggle_switch: ^2.1.0
  qr_flutter: ^4.1.0
  like_button: ^2.1.0
  font_awesome_flutter: ^10.7.0
  lite_rolling_switch: ^1.0.0
  modal_progress_hud_nsn: ^0.5.0
  flutter_slidable: ^3.0.1
  blinking_text: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/icon_android.png"
  image_path_ios: "assets/icon/icon_ios.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/screen/
    - assets/pool/

module:
  androidX: true
